[phases.setup]
nixPkgs = ["python311", "socat"]  # Python موجود، بس استدع pip عبر python3 -m

[start]
cmd = "socat -d -d TCP-LISTEN:8000,fork,reuseaddr,crnl EXEC:\"python3 -u ./Spongebob.py\",pty,setsid,ctty"
